### ISSUE TITLE
N/A instead of date and time in both current archive reports

### ISSUE THREAD

**Issue by copain60** [seehase/neowx-material#11]
There seems to be a small error in archive, which exists already in the original Neoground repo.
On current year and current month reports ONLY, always N/A is shown below the site title instead of current date and time.
All other archive reports are correct.

**Comment by W0CHP** [comment]
Known issue. Not sure why this happens.

Here's my workaround on [my site](https://wx.w0chp.net):

in [header.inc](https://github.com/seehase/neowx-material/blob/df364da3948a0d17faa7858c9a9167d6b3b0e991/src/header.inc#L20):

```python
<strong>$station.location</strong><br>
#if $active_nav is 'archive'
<span class="font-small"></span>
#else 
<span class="font-small">$current.dateTime</span>
```

If you have a better solution, feel free to submit a Pull Request.

**Comment by seehausen** [comment]
I like your aproach @W0CHP
the date field does not make sense on archive page because it is already shown
<img width="950" alt="image" src="https://user-images.githubusercontent.com/34270572/204651760-a2aaaaba-7c3b-4a04-a29d-06afa5c1d889.png">

I'll fix this

**Comment by seehausen** [comment]
Please not merge yet, there is still a bug on the month and year pages... I'll work on it

**Comment by seehase** [comment]
Changes are merged, issue can be closed
