### ISSUE TITLE
Corrupt Formatting on history.html

### ISSUE THREAD

**Issue by Pogs2004** [seehase/neowx-material#17]
Corruption of tables in history.html (see screenshot). I've noticed this twice now, the last time was at 00:05 on 01/12/2022 when a new month was added, then again at some time last night when there were changes to some of the December stats.

<img width="1951" alt="Screenshot 2022-12-14 at 08 53 18" src="https://user-images.githubusercontent.com/17429893/207553237-6f5a4760-08c6-4fa0-be54-3e901b141941.png">

It seems to sort itself out after a while, it certainly did on 01/12/2022. I have made no changes to the history.html.tmpl or skin.conf in the last few days, and the historygenerator.py hasn't been touched or changed.

**Comment by Pogs2004** [comment]
I have had to remove the max windspeed from my stats as it still remains broken. We had heavy snow on Monday which affected my ultrasonic anemometer, it recorded a gust of 146mph! I think this may be causing an issue with it, not sure.

**Comment by seehausen** [comment]
I will have a look this weekend
Thanks for reporting

**Comment by Pogs2004** [comment]
Happy New Year! I removed the erroneous wind gust from the database and now it's formatting correctly, however it is a concern that a three figure gust (which is highly possible up here) breaks the formatting, when there are plenty three figure values in the rainfall section.

I still get temperature values that are not coloured, I have played around with the min and max values but can't seem to find a range that works for all temperature values. https://www.360shetland.co.uk/weather/history.html

**Comment by seehase** [comment]
Hi @Pogs2004 
I think your problem could be a wrong color value `#05EF3D2` it has 7 digit but must be 6
![grafik](https://user-images.githubusercontent.com/3663078/213867194-d9a319b8-ee33-46ac-9a1b-a8c7e0d3b88a.png)

**Comment by Pogs2004** [comment]
Well spotted! That’s it fixed now :)

**Comment by seehase** [comment]
According to the wrong formatting
how many vallues did you correct in the DB and in which table, was it just one value, can you reproduce it.
I changed some values but did not get the same error

**Comment by Pogs2004** [comment]
It was a maximum windspeed value, IIRC it was around 200mph. I only changed a single record and that fixed it. I’ll have a look in the SQLite history to see which record it was and change it to a high value to see if it breaks it again.

**Comment by seehase** [comment]
did you changed the value in table "archive" or "archive_day_wind" or?
maybe we can reproduce and fix it

**Comment by Pogs2004** [comment]
I removed it from the archive table then rebuilt the daily summaries for that day

**Comment by seehase** [comment]
hmmm... I changed max wind speed for Jan. 2022
https://solar.seehausen.org/weewx/history.html
but chart is still not broken... maybe convertion from km/h -> mph? not sure
![grafik](https://user-images.githubusercontent.com/3663078/213874078-15c5c006-8c51-4d7a-987e-3c5273f619dd.png)

If it happens again, we can have a look before you change the database

**Comment by Pogs2004** [comment]
When I was playing around with the min, max and colour values yesterday I broke the formatting in the same way, so I think this issue is directly related to #16 with overlaps in the min and max values. I will keep an eye on it but I will close this issue now as resolved.
