### ISSUE TITLE
Station/System uptime displays in seconds can it be days?

### ISSUE THREAD

**Issue by glenosAU** [seehase/neowx-material#21]
Hi,
Its likely these are simple issues I do not understand and not related to the code.

I have updated to the latest version of neowx-material from here and found the station and system uptimes are being displayed in seconds, can they be displayed in days is this a change in the skin or footer.inc?

Thanks
Glen

**Comment by glenosAU** [comment]
I have solved the Cloudbase issue by reconfiguring the database. The schema did not have cloudbase in the archive table but has a daily summary for cloudbase by reconfiguring I have corrected the database.

**Comment by W0CHP** [comment]
> This is due to a breaking change in WeeWX 4.10

Good catch...will commit shortly. Thank you.

**Comment by glenosAU** [comment]
Thanks everyone.
